### PR TITLE
FIX: Registration html5 verification: min value miscalculated

### LINKED ISSUE #157: Registration html5 verification: min value miscalculated
The value doesn't match the value expected by the backend.

### PR DESCRIPTION
**Pull request by fapdash**
The today variable was changed by the calculation for the startDate /
max value, which changed the result of endDate.

fixes #157

### CODE REVIEW

**Comment by Nonononoki** [comment]
Is there is miscalculation? Everything is working as intended currently, you cannot change your birthdate to a date that is less than minDate and greater than maxDate

File: src/main/resources/static/js/register.js [hunk 1]
```diff
@@ -5,13 +5,15 @@ const maxAge = 99;
 $(function() {
 
 	let today = new Date();
-	let startDate = new Date(today.setFullYear(today.getFullYear() - minAge)).toISOString().split('T')[0];
```
Comment (fapdash) [inline src/main/resources/static/js/register.js:8]: This line calls `todat.setFullYear()`, which changes the return value of `today.getFullYear()` in the next line, therefore the `endDate` is offset by `minAge`.
